version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./nginx-logrotate.conf:/etc/logrotate.d/nginx-logrotate.conf
    ports:
      - "80:80"
    depends_on:
      - fe-shopapp
      - be-shopapp
    networks:
      - mynetwork
  fe-shopapp:
    image: huytg/feshopapp
    restart: unless-stopped
    tty: true
    ports:
      - "4200:4200"
    networks:
      - mynetwork
networks:
  mynetwork:
